Align on a README
whatwg/spec-factory pull request #49
Opened 2023-09-25 11:24 UTC by annevk

This doesn't cover all standards (Compatibility, Console, File System, Fullscreen, HTML, and Streams are excluded for now), but hopefully we can get there in incremental steps.

2023-09-26 04:05 UTC, domenic requested changes

2023-09-26 04:05 UTC, domenic commented on README.md.template
> +For quick local iteration, run `make`. To verify your changes locally, run `make deploy`. See more in the [WHATWG Contributor Guidelines](https://github.com/whatwg/meta/blob/main/CONTRIBUTING.md#buil
```suggestion
For quick local iteration, run `make`; this will use a web service to build the standard, so that you don't have to install anything. See more in the [WHATWG Contributor Guidelines](https://github.com/whatwg/meta/blob/main/CONTRIBUTING.md#building).
```

2023-09-26 04:05 UTC, domenic commented on README.md.template
> +## Formatting
I know these are your formatting preferences but I'd prefer not making them the universal default, without more discussion. E.g. I and other editors prefer using much more Markdown syntax.

2023-09-26 12:03 UTC, annevk commented
I think this better addresses the remaining feedback.

The idea is that you can have a shared README section across specifications that hopefully eventually we can standardize upon somehow (one way or another) and each specification also gets a READMEEND section they maintain locally and that is pulled in when doing a spec-factory deploy.

2023-09-26 14:38 UTC, annevk commented
I guess "README-addition-anne" needs to be called out in https://github.com/whatwg/spec-factory/blob/main/README.md as it doesn't end in `.template`. Perhaps we should call them something along the lines of `README.md.anne.template-part` and call out `.template-part` even though it doesn't really have any particular meaning beyond that?

2023-09-26 18:37 UTC, tabatkins commented on README-addition-anne
> +End tags may be included (if done consistently) and attributes may be quoted (using double quotes), though the prevelant theme is to omit end tags and not quote attributes (unless they contain a spac
```suggestion
End tags may be included (if done consistently) and attributes may be quoted (using double quotes), though the prevalant theme is to omit end tags and not quote attributes (unless they contain a space).
```

2023-09-27 06:38 UTC, domenic approved these changes
This seems like it'll work nicely.

I like the idea of using a different extension like `.template-part`.

2023-09-27 07:06 UTC, merged